
import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomeStyles from '@/styles/home.module.scss'
import Input from '@/components/Input'
import Translation from '@/components/Translation'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [input, setInput] = useState<string>('')
  const [translatedText, setTranslatedText] = useState<string>('')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${HomeStyles.homeContainer} ${inter.className}`}>
        <h1>Translate from English to Japanese <br/> With AI!</h1>
        <Input input={input} setInput={setInput} setTranslatedText={setTranslatedText}/>
        {translatedText[0] &&
          <Translation translatedText={translatedText} setTranslatedText={setTranslatedText}/>}
      </main>
    </>
  )
}
